---
title: "Generate phenotype text files by site for GWAS analysis"
author: "Mary T. Yohannes"
date: "2024-07-15"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

# read in files 
```{r}
# read in phenotype files with PC scores (by site) - Lerato generated these files - we mainly want the PC scores, age, and sex columns 
file_list <- list.files("~/Desktop/Broad/alicia/bge/neurogap/khat_gwas/gwas/lerato_pheno", pattern = 'NeuroGAP-Psychosis_*', full.names = T, recursive = TRUE)
df_list = lapply(file_list, read.table, sep = "\t", header = T)
names(df_list) <- gsub(".*_(.+)_.*", "\\1", basename(file_list))
pc_all <- bind_rows(df_list, .id = "file_name") %>% select(file_name, IID, PC1:PC10, age, sex) # merge the individual dfs into one and select the columns we want

# read in NeuroGAP phenotype table (not translated, still numerically coded) and filter to columns we are interested in - subj_id, assist_khat, and assist_khat_amt 
NeuroGAP_pheno_tbl <- read.csv("~/Desktop/Broad/alicia/bge/neurogap/external_datasets/NeuroGAP-P_Release8_as-of-2023-08-29.csv", na.strings=c("","NA")) %>% select(subj_id, assist_khat, assist_khat_amt) # 42953 rows and 5 columns 
```

# first join 
```{r}
# join the above two dfs on IDs that match between the two ID columns 
joined1 <- inner_join(pc_all, NeuroGAP_pheno_tbl, by= join_by(IID == subj_id)) # 3,133 matches which are all from AAU 
```

# second join 
```{r}
# subset PC df to samples that didn't have matching IDs between the NeuroGAP_pheno_tbl and PC df
unmatched_pc_meta <- pc_all[pc_all$IID %in% NeuroGAP_pheno_tbl$subj_id == FALSE,] # 31,726 unmatches 

# read in the BGE manifest table for ID matching between NeuroGAP_pheno_tbl and the PC df 
bge_manifest <- read.csv("~/Desktop/Broad/alicia/bge/neurogap/external_datasets/BGE_HailCallset_Wave2_Manifest_02202024.csv") 

# for those samples that didn't have matching IDs between the NeuroGAP_pheno_tbl and PC df, see if the IDs in the PC df match to the SUBJECT_ID column in the BGE manifest and join tables accordingly 
pc_manifest_joined <- inner_join(unmatched_pc_meta, bge_manifest, by= join_by(IID == SUBJECT_ID)) # 23,923 matches 

# check if the samples in pc_manifest_joined are part of the NeuroGAP_pheno_tbl - use COLLABORATOR_PARTICIPANT_ID column (which we got from the manifest file) to match to the subj_id column in the NeuroGAP_pheno_tbl. There are two samples with lowercases in COLLABORATOR_PARTICIPANT_ID so update that before joining 
joined2 <- pc_manifest_joined %>% mutate(COLLABORATOR_PARTICIPANT_ID = toupper(COLLABORATOR_PARTICIPANT_ID)) %>% inner_join(NeuroGAP_pheno_tbl, by= join_by(COLLABORATOR_PARTICIPANT_ID == subj_id)) # 23,922 matches 

# 1 unmatch - COLLABORATOR_PARTICIPANT_ID == MAP53366857 OR SUBJECT_ID == MAP3543
pc_manifest_joined[toupper(pc_manifest_joined$COLLABORATOR_PARTICIPANT_ID) %in% NeuroGAP_pheno_tbl$subj_id == FALSE,] 

# Toni ran KING a few months ago on the entire NeuroGAP dataset to find duplicates and looks like MAP3543 (MAP53366857) is a duplicate with MAP457 (MAP24388084) 
```

# third join 
```{r}
# from the samples that didn't have matching IDs between the NeuroGAP_pheno_tbl and PC df, filter those that had unmatches between the IDs in the PC df and BGE manifest (SUBJECT_ID column) 
unmatched_pc_manifest <- unmatched_pc_meta[unmatched_pc_meta$IID %in% bge_manifest$SUBJECT_ID == FALSE,] # 7,803 unmatches which are all from UCT

# read in edited sample IDs file - Toni generated this file because there were inconsistencies among sample IDs (for ex. "_" instead of "-") which created issues with ID matching particularly with the UCT samples   
edited_ids <- read.csv("~/Desktop/Broad/alicia/bge/neurogap/external_datasets/NeuroGAP_edited_ids.txt", sep = "\t") 

# see if the samples that didn't match SUBJECT_ID column in the BGE manifest match with the old_within_fam column in the edited_ids table. For the samples that match, add on the columns from the edited_ids table 
pc_edited_ids <- inner_join(unmatched_pc_manifest, edited_ids, by= join_by(IID == old_within_fam)) # 7,803 matches 

# see if the newly added IDs from edited_ids table match to SUBJECT_ID column in the BGE manifest and join tables accordingly 
pc_edited_manifest_joined <- inner_join(pc_edited_ids, bge_manifest, by= join_by(FID == SUBJECT_ID)) # 7,803 matches 

# check if the samples in pc_edited_manifest_joined are part of the NeuroGAP_pheno_tbl - use COLLABORATOR_PARTICIPANT_ID column (which we got from the manifest file) to match to the subj_id column in the NeuroGAP_pheno_tbl. There are two samples with lowercases in COLLABORATOR_PARTICIPANT_ID so update that before joining 
joined3 <- pc_edited_manifest_joined %>% mutate(COLLABORATOR_PARTICIPANT_ID = toupper(COLLABORATOR_PARTICIPANT_ID)) %>% inner_join(NeuroGAP_pheno_tbl, by= join_by(COLLABORATOR_PARTICIPANT_ID == subj_id)) # 7,801 matches 

# 2 unmatches - IIDs == NGP5915-1OWL and NGP5434-1XJK
pc_edited_manifest_joined[toupper(pc_edited_manifest_joined$COLLABORATOR_PARTICIPANT_ID) %in% NeuroGAP_pheno_tbl$subj_id == FALSE,]

# Toni ran KING a few months ago on the entire NeuroGAP dataset to find duplicates and looks like NGP5915-1OWL is a duplicate with NGP5844-1MDL. However, NGP5434-1XJK does not have a duplicate and we have no idea why we can't find it in the NeuroGAP_pheno_tbl - excluded from subsequent analysis 
```

# final join 
```{r}
# join the three joined tables together using the columns they intersect on to generate the final phenotype df 
commcols <- intersect(names(joined1), names(joined2)) # common columns between the first two joined dfs 
final_joined <- bind_rows(
    select(joined1, all_of(commcols)),
    select(joined2, all_of(commcols)),
    select(joined3, all_of(commcols))
)

# sanity check
nrow(pc_all) - 3 == nrow(final_joined) # TRUE
```

# address duplicates before writing out GWAS phenotype tables  
```{r}
# MAP3543 / MAP53366857 is a duplicate with MAP457 / MAP24388084 
# NGP5915-1OWL / NGP5915.1OWL / WSP56673406 is a duplicate with NGP5844-1MDL / NGP5844.1MDL / WSP54956766  
# NGP5434-1XJK isn't present in the NeuroGAP_pheno_tbl and doesn't have a duplicate so it will be excluded from subsequent analysis

# for the two samples that didn't have a match in the NeuroGAP_pheno_tbl, add their duplicate samples' info to the final phenotype df  
duplicates <- pc_all %>% filter(IID == "MAP3543" | IID == "NGP5915-1OWL")
final_joined <- rbind(final_joined, 
                      cbind(duplicates,
                            NeuroGAP_pheno_tbl %>% filter(subj_id == "MAP24388084" | subj_id == "WSP54956766")) %>% 
                        select(-subj_id)
                      )

# reorder table to match PC file 
final_joined <- final_joined[ order(match(final_joined$IID, pc_all$IID)), ]

# sanity check 
nrow(pc_all) - 1 == nrow(final_joined) # TRUE

####### notes ####### 
# the two unmatched UCT samples (NGP5915-1OWL, NGP5434-1XJK) and sample MAP7901 from Uganda don't have age recorded in the PC file (file with covariates) so have NA values in the GWAS phenotype files - age_at_iview for NGP5844-1MDL (WSP54956766), the duplicate of NGP5915-1OWL (WSP56673406), is 39 in the NeuroGAP phenotype file (NeuroGAP_pheno_tbl)
# sample MAP53366857 age is 33 in the PC file while age_at_iview for it's duplicate MAP24388084 is 32 in the NeuroGAP_pheno_tbl - used what was in the the PC file
```

# subset final phenotype df by site and write out final phenotype files by site 
```{r}
for (site_name in names(table(final_joined$file_name))){
  pheno_site <- final_joined %>% filter(file_name == site_name) %>% select(-file_name)
  #write.table(pheno_site, paste0("~/Desktop/Broad/alicia/bge/neurogap/khat_gwas/gwas/phenotype_files/", site_name, "_khat_pheno.txt"), row.names = F, sep = " ", quote = F)
  print(paste0("finished writing out ", site_name, " ", nrow(pheno_site)))
}
```






