---
title: "Generate manhattan_plot"
author: "Mary T. Yohannes"
date: "2024-07-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(topr) # https://github.com/totajuliusd/topr/blob/master/man/figures/manhattan_wide_1080_high.gif
library(dplyr)
library('qqman')
library('car')
```


```{r}
# read in output from meta-analysis - huge file so will take a bit of time to read file 
assist_khat_amt <- read.csv('~/Desktop/Broad/alicia/bge/neurogap/khat_gwas/gwas/results/saige_assist_khat_amt_LOCO.meta', sep = '\t')
assist_khat <- read.csv('~/Desktop/Broad/alicia/bge/neurogap/khat_gwas/gwas/results/saige_assist_khat_LOCO.meta', sep = '\t')



#manhattan(assist_khat_amt) - takes a long time to run
#manhattan(assist_khat_amt, annotate=5e-8)

manhattan(assist_khat, annotate=5e-8)
n <-assist_khat %>% get_lead_snps() %>% annotate_with_nearest_gene()


m <-assist_khat_amt %>% get_lead_snps() %>% annotate_with_nearest_gene()

#qqPlot(assist_khat_amt$P)

qqnorm(assist_khat$P);qqline(assist_khat$P)

rbind(n,m)


eight <- assist_khat %>% filter(CHR == 8)

write.table(eight, '~/Desktop/Broad/alicia/bge/neurogap/khat_gwas/gwas/results/eight.tsv', sep = '\t', row.names = F, col.names = T)




```





